name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
        docker build -t bala-flask-app:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag bala-flask-app:$IMAGE_TAG 443427140918.dkr.ecr.ap-south-1.amazonaws.com/bala-flask-app:$IMAGE_TAG

      - name: Push image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push 443427140918.dkr.ecr.ap-south-1.amazonaws.com/bala-flask-app:$IMAGE_TAG

      - name: Store image tag in SSM
        run: |
        aws ssm put-parameter \
      --name "/bala/flask-app/image-tag" \
      --value "${{ github.sha }}" \
      --type String \
      --overwrite \
      --region ap-south-1

      - name: Trigger Instance Refresh
      run: |
      aws autoscaling start-instance-refresh \
      --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
      --preferences '{
        "MinHealthyPercentage": 90,
        "InstanceWarmup": 180
      }' \
      --region ap-south-1
