name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t bala-flask-app .

      - name: Tag Docker image
        run: |
          docker tag bala-flask-app:latest 443427140918.dkr.ecr.ap-south-1.amazonaws.com/bala-flask-app:latest

      - name: Push image to ECR
        run: |
          docker push 443427140918.dkr.ecr.ap-south-1.amazonaws.com/bala-flask-app:latest
      - name: Trigger Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
          --auto-scaling-group-name terraform-20260310123743037100000003
